### ISSUE TITLE
sourceMaps

### ISSUE THREAD

**Issue by mikejw** [mihhail-lapushkin/react-scripts-x#4]
Hi there,

Is there a way to configure PostCSS sourceMaps (with CRA) when using react-scripts-x?

Thanks!

**Comment by mihhail-lapushkin** [comment]
Hey,

`config` is proxied to plugins like so:
```
require('plugin')(config)
```
So if PostCSS supports configuring source maps via the object that you give it, then it works.

**Comment by mikejw** [comment]
Can that code go anywhere?  So far I am only providing config in my package.json file:

 ```
"react-scripts-x": {
    "postcss": [
      {
        "name": "postcss-conditionals"
      },
      {
        "name": "postcss-import"
      },
      {
        "name": "postcss-at-rules-variables"
      },
      {
        "name": "postcss-css-variables"
      },
      {
        "name": "postcss-for"
      },
      {
        "name": "postcss-each"
      },
      {
        "name": "lost"
      },
      {
        "name": "postcss-nested"
      },
      {
        "name": "postcss-custom-media"
      },
      {
        "name": "autoprefixer"
      }
    ]
  }
```

**Comment by mihhail-lapushkin** [comment]
See example in the README:
https://github.com/mihhail-lapushkin/react-scripts-x

You can also specify the `config`, not only `name`.

**Comment by mikejw** [comment]
Sorry but I'm not sure which plugin I need to configure.  I'm not using postcss-loader but maybe I should be?

**Comment by mihhail-lapushkin** [comment]
Oh, sorry, I missed the fact that it's not a plugin, but a general config of PostCSS.

This is handled by react-scripts:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js
```
      {
        // Options for PostCSS as we reference these options twice
        // Adds vendor prefixing based on your specified browser support in
        // package.json
        loader: require.resolve('postcss-loader'),
        options: {
          // Necessary for external CSS imports to work
          // https://github.com/facebook/create-react-app/issues/2677
          ident: 'postcss',
          plugins: () => [
            require('postcss-flexbugs-fixes'),
            require('postcss-preset-env')({
              autoprefixer: {
                flexbox: 'no-2009',
              },
              stage: 3,
            }),
            // Adds PostCSS Normalize as the reset css with default options,
            // so that it honors browserslist config in package.json
            // which in turn let's users customize the target behavior as per their needs.
            postcssNormalize(),
          ],
          sourceMap: isEnvProduction && shouldUseSourceMap,
        },
```
It seems that source maps are generated only for production builds.

**Comment by mikejw** [comment]
Cool, thanks!  I read this somewhere else too but it still didn't click that CRA has native support for postcss, to a certain degree.  (For autoprefixer, I suppose.)

What I was looking for was complete control of sourceMap generation and this trick provides a substitute for that: https://github.com/mars/create-react-app-buildpack/issues/59#issuecomment-316354389.

Thanks again.
